---
- name: Run show on Cisco IOS
  hosts: R1
  gather_facts: no
  connection: network_cli
  become: yes
  become_method: enable

  vars:
    ansible_user: mohamed
    ansible_ssh_pass: cisco
    ansible_become_pass: cisco
    ansible_network_os: ios



  tasks:
    - name: Run privileged commands
      ios_command:
        commands:
          - show run
      register: print_output

    - debug: var=print_output.stdout_lines
...
