---
- name: Running show commands on Cisco IOS
  hosts: R1
  gather_facts: false
  connection: network_cli

  tasks:
    - name: Run multiple commands on Cisco IOS nodes
      ios_command:
        commands:
          - show version

      register: print_output

    - debug: var=print_output.stdou_lines
...
